[2024-01-05T06:40:57.424+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-05T05:28:00+00:00 [queued]>
[2024-01-05T06:40:57.493+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-05T05:28:00+00:00 [queued]>
[2024-01-05T06:40:57.497+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-05T06:40:57.964+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_orders> on 2024-01-05 05:28:00+00:00
[2024-01-05T06:40:58.016+0000] {standard_task_runner.py:57} INFO - Started process 948 to run task
[2024-01-05T06:40:58.047+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_orders', 'scheduled__2024-01-05T05:28:00+00:00', '--job-id', '3525', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpl9dltz9e']
[2024-01-05T06:40:58.054+0000] {standard_task_runner.py:85} INFO - Job 3525: Subtask insert_into_orders
[2024-01-05T06:40:58.390+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_orders scheduled__2024-01-05T05:28:00+00:00 [running]> on host 439392e7318f
[2024-01-05T06:40:58.972+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-01-05T05:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-05T05:28:00+00:00'
[2024-01-05T06:40:59.000+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Orders (customer_id, order_date)
    VALUES
        (1, NOW()),
        ( 2, NOW())
[2024-01-05T06:40:59.050+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-05T06:40:59.096+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-05T06:40:59.234+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Orders (customer_id, order_date)
    VALUES
        (1, NOW()),
        ( 2, NOW()), parameters: None
[2024-01-05T06:40:59.247+0000] {sql.py:427} INFO - Rows affected: 2
[2024-01-05T06:40:59.284+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_orders, execution_date=20240105T052800, start_date=20240105T064057, end_date=20240105T064059
[2024-01-05T06:40:59.392+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-05T06:40:59.490+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
