[2024-01-04T12:08:01.126+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns manual__2024-01-04T11:59:21.453536+00:00 [queued]>
[2024-01-04T12:08:01.148+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns manual__2024-01-04T11:59:21.453536+00:00 [queued]>
[2024-01-04T12:08:01.149+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-01-04T12:08:01.173+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_product_returns> on 2024-01-04 11:59:21.453536+00:00
[2024-01-04T12:08:01.180+0000] {standard_task_runner.py:57} INFO - Started process 509 to run task
[2024-01-04T12:08:01.187+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_product_returns', 'manual__2024-01-04T11:59:21.453536+00:00', '--job-id', '233', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpleqp41lc']
[2024-01-04T12:08:01.189+0000] {standard_task_runner.py:85} INFO - Job 233: Subtask insert_into_product_returns
[2024-01-04T12:08:01.272+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_product_returns manual__2024-01-04T11:59:21.453536+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:08:01.417+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_product_returns' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T11:59:21.453536+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-04T11:59:21.453536+00:00'
[2024-01-04T12:08:01.418+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;
[2024-01-04T12:08:01.434+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:08:01.458+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:08:01.640+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;, parameters: None
[2024-01-04T12:08:01.645+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:08:01.667+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_product_returns, execution_date=20240104T115921, start_date=20240104T120801, end_date=20240104T120801
[2024-01-04T12:08:01.721+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:08:01.754+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
