[2024-01-04T12:17:56.012+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T05:40:00+00:00 [queued]>
[2024-01-04T12:17:56.174+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T05:40:00+00:00 [queued]>
[2024-01-04T12:17:56.189+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:17:56.582+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_product_returns> on 2024-01-04 05:40:00+00:00
[2024-01-04T12:17:56.619+0000] {standard_task_runner.py:57} INFO - Started process 314 to run task
[2024-01-04T12:17:56.646+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_product_returns', 'scheduled__2024-01-04T05:40:00+00:00', '--job-id', '522', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpd2ps_4yy']
[2024-01-04T12:17:56.652+0000] {standard_task_runner.py:85} INFO - Job 522: Subtask insert_into_product_returns
[2024-01-04T12:17:56.949+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T05:40:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:17:57.387+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_product_returns' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T05:40:00+00:00'
[2024-01-04T12:17:57.397+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;
[2024-01-04T12:17:57.471+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:17:57.513+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:17:57.654+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;, parameters: None
[2024-01-04T12:17:57.660+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:17:57.694+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_product_returns, execution_date=20240104T054000, start_date=20240104T121756, end_date=20240104T121757
[2024-01-04T12:17:57.783+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:17:57.879+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
