[2024-01-04T12:09:43.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T02:50:00+00:00 [queued]>
[2024-01-04T12:09:43.554+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T02:50:00+00:00 [queued]>
[2024-01-04T12:09:43.556+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:09:43.618+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_product_returns> on 2024-01-04 02:50:00+00:00
[2024-01-04T12:09:43.633+0000] {standard_task_runner.py:57} INFO - Started process 729 to run task
[2024-01-04T12:09:43.652+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_product_returns', 'scheduled__2024-01-04T02:50:00+00:00', '--job-id', '330', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpm7k3qxvv']
[2024-01-04T12:09:43.656+0000] {standard_task_runner.py:85} INFO - Job 330: Subtask insert_into_product_returns
[2024-01-04T12:09:43.868+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T02:50:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:09:44.222+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_product_returns' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T02:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T02:50:00+00:00'
[2024-01-04T12:09:44.230+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;
[2024-01-04T12:09:44.270+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:09:44.312+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:09:44.476+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;, parameters: None
[2024-01-04T12:09:44.486+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:09:44.527+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_product_returns, execution_date=20240104T025000, start_date=20240104T120943, end_date=20240104T120944
[2024-01-04T12:09:44.779+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:09:44.879+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
