[2024-01-04T12:18:54.320+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T07:10:00+00:00 [queued]>
[2024-01-04T12:18:54.344+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T07:10:00+00:00 [queued]>
[2024-01-04T12:18:54.345+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-04T12:18:54.379+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_product_returns> on 2024-01-04 07:10:00+00:00
[2024-01-04T12:18:54.386+0000] {standard_task_runner.py:57} INFO - Started process 494 to run task
[2024-01-04T12:18:54.394+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_product_returns', 'scheduled__2024-01-04T07:10:00+00:00', '--job-id', '611', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpf2li_das']
[2024-01-04T12:18:54.397+0000] {standard_task_runner.py:85} INFO - Job 611: Subtask insert_into_product_returns
[2024-01-04T12:18:54.526+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_product_returns scheduled__2024-01-04T07:10:00+00:00 [running]> on host 399e7321ffbc
[2024-01-04T12:18:54.744+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_product_returns' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T07:10:00+00:00'
[2024-01-04T12:18:54.748+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;
[2024-01-04T12:18:54.773+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:18:54.795+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-04T12:18:55.004+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Product_returns (return_id, customer_id, return_date)
    VALUES
        (1, 1, NOW() - INTERVAL '1 minute'),
        (2, 2, NOW() - INTERVAL '1 minute')
    ON CONFLICT (return_id) DO NOTHING;, parameters: None
[2024-01-04T12:18:55.010+0000] {sql.py:427} INFO - Rows affected: 0
[2024-01-04T12:18:55.042+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_product_returns, execution_date=20240104T071000, start_date=20240104T121854, end_date=20240104T121855
[2024-01-04T12:18:55.135+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-04T12:18:55.186+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
