[2024-01-05T06:29:48.995+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T18:48:00+00:00 [queued]>
[2024-01-05T06:29:49.016+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T18:48:00+00:00 [queued]>
[2024-01-05T06:29:49.042+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-01-05T06:29:49.117+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): insert_into_orders> on 2024-01-04 18:48:00+00:00
[2024-01-05T06:29:49.128+0000] {standard_task_runner.py:57} INFO - Started process 1080 to run task
[2024-01-05T06:29:49.140+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Task4', 'insert_into_orders', 'scheduled__2024-01-04T18:48:00+00:00', '--job-id', '2675', '--raw', '--subdir', 'DAGS_FOLDER/Airflow-task-3.py', '--cfg-path', '/tmp/tmpc9tq288n']
[2024-01-05T06:29:49.145+0000] {standard_task_runner.py:85} INFO - Job 2675: Subtask insert_into_orders
[2024-01-05T06:29:49.477+0000] {task_command.py:416} INFO - Running <TaskInstance: Task4.insert_into_orders scheduled__2024-01-04T18:48:00+00:00 [running]> on host 73272df13e14
[2024-01-05T06:29:50.057+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jagan' AIRFLOW_CTX_DAG_ID='Task4' AIRFLOW_CTX_TASK_ID='insert_into_orders' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T18:48:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T18:48:00+00:00'
[2024-01-05T06:29:50.125+0000] {sql.py:274} INFO - Executing: 
    INSERT INTO Orders (customer_id, order_date)
    VALUES
        (1, NOW()),
        ( 2, NOW())
[2024-01-05T06:29:50.180+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-05T06:29:50.220+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-01-05T06:29:50.436+0000] {sql.py:418} INFO - Running statement: 
    INSERT INTO Orders (customer_id, order_date)
    VALUES
        (1, NOW()),
        ( 2, NOW()), parameters: None
[2024-01-05T06:29:50.487+0000] {sql.py:427} INFO - Rows affected: 2
[2024-01-05T06:29:50.588+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Task4, task_id=insert_into_orders, execution_date=20240104T184800, start_date=20240105T062948, end_date=20240105T062950
[2024-01-05T06:29:50.710+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-01-05T06:29:50.815+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
